config/routes.rb
Sifaca::Application.routes.draw do
  devise_for :users

  resources :clients

  resources :resumes

  resources :articles

  resources :invoices

  resources :folios

  root :to => 'index#index'

   match 'index/dashboard' => 'index#dashboard', :as => :dashboard

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_many :articles
  has_one :resume
  has_one :folio
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.json
  def new
    @invoice = Invoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(params[:invoice])

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render json: @invoice, status: :created, location: @invoice }
      else
        format.html { render action: "new" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.json
  def update
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for @invoice, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Invoice</legend>

    <div class="control-group">
      <%= f.label :date, :class => 'control-label' %>
      <div class="controls">
        <%= f.date_select :date, :class => 'date_select' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :client_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select :client_id, Client.all, :id, :name  %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :folio_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :folio_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', invoices_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/invoices/edit.html.erb
<%= render :partial => 'form' %>

app/views/invoices/index.html.erb
<h1>Invoices</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Date</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.id %></td>
        <td><%= link_to invoice.date, invoice_path(invoice) %></td>
        <td><%= invoice.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_invoice_path(invoice), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', invoice_path(invoice), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_invoice_path, :class => 'btn btn-primary' %>

app/views/invoices/new.html.erb
<%= render :partial => 'form' %>

app/views/invoices/show.html.erb
<h1>Invoice</h1>

<p>
  <b>Date</b><br>
  <%= @invoice.date %>
</p>

<p>
  <b>Client</b><br>
  <%= @invoice.client_id %>
</p>

<p>
  <b>Folio</b><br>
  <%= @invoice.folio_id %>
</p>

<div class="form-actions">
  <%= link_to 'Back', invoices_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_invoice_path(@invoice), :class => 'btn' %>
  <%= link_to 'Delete', invoice_path(@invoice), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>