config/routes.rb
Sifaca::Application.routes.draw do
  devise_for :users

  resources :clients

  resources :resumes

  resources :articles

  resources :invoices

  resources :folios

  root :to => 'index#index'

   match 'index/dashboard' => 'index#dashboard', :as => :dashboard

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :invoice
  #has_one :invoice
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resumes }
    end
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
    @resume = Resume.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/new
  # GET /resumes/new.json
  def new
    @resume = Resume.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/1/edit
  def edit
    @resume = Resume.find(params[:id])
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(params[:resume])

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render json: @resume, status: :created, location: @resume }
      else
        format.html { render action: "new" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update
    @resume = Resume.find(params[:id])

    respond_to do |format|
      if @resume.update_attributes(params[:resume])
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy

    respond_to do |format|
      format.html { redirect_to resumes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= form_for @resume, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Resume</legend>

    <div class="control-group">
      <%= f.label :iva, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :iva, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :subtotal, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :subtotal, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :total, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :total, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :invoice_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :invoice_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :letter_number, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :letter_number, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :payment_condition, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :payment_condition, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :receipt, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :receipt, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', resumes_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/resumes/edit.html.erb
<%= render :partial => 'form' %>

app/views/resumes/index.html.erb
<h1>Resumes</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Factura</th>
      <th>Cliente</th>
      <th>RFC</th>
      <th>Subtotal</th>
      <th>IVA</th>
      <th>Total</th>
      <th>Tipo Pago</th>
      <th>Fecha Pago</th>
      <th>Tipo Venta</th>
    </tr>
  </thead>
  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.invoice_id %></td>
        <td><%= Client.find(Invoice.find(resume.invoice_id).client_id).name %></td>
        <td><%= Client.find(resume.invoice_id).rfc %></td>
        <td><%= resume.subtotal %></td>
        <td><%= resume.iva %></td>
        <td><%= resume.total %></td>
        <td><%= resume.payment_condition %></td>
        <td><%= resume.created_at %></td>
        <td><%= resume.receipt %></td>
        <td>
          <%= link_to 'Show', resume_path(resume), :class => 'btn btn-mini' %>
          <%= link_to 'Edit', edit_resume_path(resume), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', resume_path(resume), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_resume_path, :class => 'btn btn-primary' %>

app/views/resumes/new.html.erb
<%= render :partial => 'form' %>

app/views/resumes/show.html.erb
<h1>Resume</h1>

<p>
  <b>Iva</b><br>
  <%= @resume.iva %>
</p>

<p>
  <b>Subtotal</b><br>
  <%= @resume.subtotal %>
</p>

<p>
  <b>Total</b><br>
  <%= @resume.total %>
</p>

<p>
  <b>Invoice</b><br>
  <%= @resume.invoice_id %>
</p>

<p>
  <b>Letter number</b><br>
  <%= @resume.letter_number %>
</p>

<p>
  <b>Payment condition</b><br>
  <%= @resume.payment_condition %>
</p>

<p>
  <b>Receipt</b><br>
  <%= @resume.receipt %>
</p>

<div class="form-actions">
  <%= link_to 'Back', resumes_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_resume_path(@resume), :class => 'btn' %>
  <%= link_to 'Delete', resume_path(@resume), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>