config/routes.rb
Sifaca::Application.routes.draw do
  devise_for :users

  resources :clients

  resources :resumes

  resources :articles

  resources :invoices

  resources :folios

  root :to => 'index#index'

   match 'index/dashboard' => 'index#dashboard', :as => :dashboard

end

app/models/folio.rb
class Folio < ActiveRecord::Base
  belongs_to :client
  belongs_to :invoice

end

app/controllers/folios_controller.rb
class FoliosController < ApplicationController
  before_filter :authenticate_user!
  # GET /folios
  # GET /folios.json
  def index
    @folios = Folio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @folios }
    end
  end

  # GET /folios/1
  # GET /folios/1.json
  def show
    @folio = Folio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @folio }
    end
  end

  # GET /folios/new
  # GET /folios/new.json
  def new
    @folio = Folio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @folio }
    end
  end

  # GET /folios/1/edit
  def edit
    @folio = Folio.find(params[:id])
  end

  # POST /folios
  # POST /folios.json
  def create
    @folio = Folio.new(params[:folio])

    respond_to do |format|
      if @folio.save
        format.html { redirect_to @folio, notice: 'Folio was successfully created.' }
        format.json { render json: @folio, status: :created, location: @folio }
      else
        format.html { render action: "new" }
        format.json { render json: @folio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /folios/1
  # PUT /folios/1.json
  def update
    @folio = Folio.find(params[:id])

    respond_to do |format|
      if @folio.update_attributes(params[:folio])
        format.html { redirect_to @folio, notice: 'Folio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @folio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folios/1
  # DELETE /folios/1.json
  def destroy
    @folio = Folio.find(params[:id])
    @folio.destroy

    respond_to do |format|
      format.html { redirect_to folios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/folios_helper.rb
module FoliosHelper
end

app/views/folios/_form.html.erb
<%= form_for @folio, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Folio</legend>

    <div class="control-group">
      <%= f.label :client_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :client_id, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :folio, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :folio, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :status, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :status, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', folios_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/folios/edit.html.erb
<%= render :partial => 'form' %>

app/views/folios/index.html.erb
<h1>Folios</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Client</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @folios.each do |folio| %>
      <tr>
        <td><%= folio.id %></td>
        <td><%= link_to folio.client_id, folio_path(folio) %></td>
        <td><%= folio.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_folio_path(folio), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', folio_path(folio), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_folio_path, :class => 'btn btn-primary' %>

app/views/folios/new.html.erb
<%= render :partial => 'form' %>

app/views/folios/show.html.erb
<h1>Folio</h1>

<p>
  <b>Client</b><br>
  <%= @folio.client_id %>
</p>

<p>
  <b>Folio</b><br>
  <%= @folio.folio %>
</p>

<p>
  <b>Status</b><br>
  <%= @folio.status %>
</p>

<div class="form-actions">
  <%= link_to 'Back', folios_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_folio_path(@folio), :class => 'btn' %>
  <%= link_to 'Delete', folio_path(@folio), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>